services:
  pidibot-dev:
    container_name: "pidibot_dev"
    image: "pidibot:latest"
    volumes:
      - ./data:/app/data
      - ./pidibot-sheets.json:/app/pidibot-sheets.json
    environment:
      - TOKEN=$TOKEN
